### ISSUE TITLE
TypeError: redisCache.after is not a function

### ISSUE THREAD

**Issue by corepay** [sarkistlt/feathers-redis-cache#10]
Hello,

I am trying to figure out how to store a User in Redis to reference from other feathers servers in network.  Can't seem to get this package to work.  

Fresh install of Feathers server and `feathers-redis-cache` results in the following:

Error
![image](https://user-images.githubusercontent.com/48992923/87466523-640cd780-c5e4-11ea-94ca-ae76df602068.png)

My app.js
![image](https://user-images.githubusercontent.com/48992923/87466444-42135500-c5e4-11ea-9eb4-29a1deee54db.png)

My users hooks
![image](https://user-images.githubusercontent.com/48992923/87466324-12fce380-c5e4-11ea-8736-6a1ec51cb79b.png)

My package.json dependencies:

![image](https://user-images.githubusercontent.com/48992923/87466830-f8773a00-c5e4-11ea-9ea6-7d5a063b83fe.png)

**Comment by sarkistlt** [comment]
@corepay can you try ```const redisCache = require('feathers-redis-cache').default```

**Comment by corepay** [comment]
:( same result

![image](https://user-images.githubusercontent.com/48992923/87483867-cd034800-c602-11ea-931f-1dc427ee6f1d.png)

**Comment by sarkistlt** [comment]
weird, it looks like issue with how you compile your code, we are using same version on several production projects without any issue. Try to debug, reinstall package, `console.log(redisCache)` to see if it imports anything at all from the module.

**Comment by johnatspreadstreet** [comment]
When running a console.log on redisCache, it produces the following:

![image](https://user-images.githubusercontent.com/37089166/87949110-9a7aa480-ca73-11ea-86c3-252e9ca9b5cf.png)

So it seems that doing `require('feathers-redis-cache').hooks` would do the trick.

@sarkistlt Is this intentional?

**Comment by sarkistlt** [comment]
@johnatspreadstreet yes you are right, sorry my bad, have a typo in readme file. in my case with TS, this is what import looks like `import { hooks as cacheHook } from 'feathers-redis-cache';` then `cacheHook.before()`

**Comment by sarkistlt** [comment]
@corepay closing the issue, since it was incorrect import due to typo in the package description, feel free to reopen if it's still doesn't work for some reason.
