### ISSUE TITLE
Best way to use with fastjoin?

### ISSUE THREAD

**Issue by dottodot** [sarkistlt/feathers-redis-cache#2]
Just wondering if you have any suggestions for the best way to use with fastjoin. I'm assuming it should implemented after the fastjoin but I don't want fastjoin to then run on a cached response as that would defeat the purpose.

Would this be the correct way to do it?

```
    get: [
      isNot(hook => hook.params.$skipCacheHook, fastJoin(viewResolver)),
      redisCache.hooks.after({ expiration: 3600 * 24 * 7 })
    ],
```

**Comment by sarkistlt** [comment]
Hi @dottodot , I haven't use fastjoin, the way cache hooks works, if you put `redisCache.hooks.after` after all your hooks, on first request it will cache the final result then on next call if request are identical (same, id or query) it will return result from before hooks `redisCache.hooks.before` so fastjoin won't be executed on the cached result.

**Comment by dottodot** [comment]
OK I not sure if something isn't working correctly then as in the following example the decorateView hooks are still being run when the result is returned from the cache
```
const decorateView = [
  fastJoin(viewResolver, context => viewQuery[context.params.schema]),
  serialize(serializeSchema)
];
```
```
    get: [
      ...decorateView,
      redisCache.hooks.after({ expiration: 3600 * 24 * 7 })
    ],
```

**Comment by sarkistlt** [comment]
@dottodot from your snippet I don't understand if ` get: [` is before or after hook.
It suppose to be after hook, then you also need before hook `get: [redisCache.hooks.before()]`

**Comment by dottodot** [comment]
That snippet is the after hook and I do already have the before hook.

**Comment by dottodot** [comment]
I'm wondering if it's because I have another before hook that sets the `hook.result`

**Comment by sarkistlt** [comment]
before hook, whenever data is populated from the cache adds new property to params, `$skipCacheHook = true`, so in after hooks you can check if `context.params.$skipCacheHook` skip the hook.

**Comment by dottodot** [comment]
I can confirm I have this working now. Here's an example.

```
      iff(
        isNot(hook => hook.params.$skipCacheHook),
        ...decorateView
      ),
```
