### ISSUE TITLE
Group list grows indefinitely

### ISSUE THREAD

**Issue by felipou** [sarkistlt/feathers-redis-cache#5]
Hi! First of all, nice project you got here, thanks for sharing it :)

We tried using this hook in a project we're about to finish, but when we did some load testing, we found some problems that cause slowdown and high memory usage.

After noticing these problems and finding the issue, I saw in your TODO list this: "option in after hook to set limit of keys per group". I believe that is a must for a production environment.

But anyways, that is not the problem per se (although it's closely related).

After many load tests, I noticed that the group list in redis was huge. When I analyzed the code, I noticed two things that contribute to this problem:
- The group list itself is not purged after deleting all the entries that it refers too, so it grows indefinitely
- The group list is not checked when pushing a new entry, so it allows for duplicate entries. At first it may not seem a problem, but it makes the first problem more impactful, because after a purge, everything in the list may be duplicated. If the group list is in fact correctly purged all the time, this should not be a problem at all, because theoretically you wouldn't get to an after hook if that path is in fact cached. But this could in fact happen a lot in a distributed environment, where you have multiple instances of your API purging and caching simultaneously.

I suggest that instead of creating the group list, maybe put the group as a cache key prefix, and when purging, just use the "keys" function to find all keys related to that group. Some care would have to be taken to avoid problems with groups named with a same prefix and things like that. I haven't exactly put a lot of thought into this, but these were the first things that came to my mind.

I may find some time in the near future to make a pull request addressing this issue, but I believe caching won't be a priority for us at the moment, so it may take some time.

**Comment by sarkistlt** [comment]
Hi @felipou just published new version with the following updates:
- use hashCode, to significantly shorter the key and group names
- use unlink (requires redis 4+) instead of del. so it won't block db and will be propagated in the background
- reorganize key grouping, add group name as a part of the key, so for purging cache I can use `scan` and avoid problem with duplicated keys per group

**Comment by felipou** [comment]
Nice, that was fast :)
